[package]
name = "dualsense-controller"
version = "0.2.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/sphereflow/dualsense-controller"
keywords = ["playstation", "dualsense", "hid", "gamepad", "controller"]
categories = ["hardware-support", "game-development"]
description = "Rust library for interfacing with a PS5 dualsense controller over USB and Bluetooth."

[dependencies]
thiserror = "2.0.18"
zerocopy = { version = "0.8.48", features = ["derive"] }
hidapi = "2.6.5"
crossbeam-channel = "0.5.15"
crc32fast = "1.5.0"
bitflags = "2"
